version: "3"

services:
  passport_checker:
    container_name: passport_checker
    hostname: passport_checker
    build: ./passport_checker
    volumes:
      - ./passport_checker/app:/app
    working_dir: /app
    ports:
      - 3500:3500
    stdin_open: true

  mongo_api:
    container_name: mongo_api
    hostname: mongo_api
    build: ./mongo_api
    volumes:
      - ./mongo_api/app:/app
    working_dir: /app
    ports:
      - 3501:3501
    stdin_open: true

  mqtt_api:
    container_name: mqtt_api
    hostname: mqtt_api
    build: ./mqtt_api
    volumes:
      - ./mqtt_api/app:/app
    working_dir: /app
    ports:
      - 3502:3502
    stdin_open: true

  fake_esp:
    container_name: fake_esp
    hostname: fake_esp
    build: ./ressources/fake_esp
    environment:
      - http_proxy
      - https_proxy

  mqtt_server:
    container_name: mqtt_server
    image: eclipse-mosquitto:1.5.4
    ports:
      - "3503:1883"
      - "3504:9001"
      
  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: 'mongo:4.1'
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
networks:
  default:
    driver: bridge
